# config/meta.yml

meta_product_name: "TreeTasker"

meta_title: "TreeTasker - Plant a tree and get things done!"

meta_description: "When you complete a task with our clutterfree experience, you will plant a tree in your virtual garden and in real life with a local garden shop of your choice."

meta_image: "cover.png" # should exist in `app/assets/images/`

twitter_account: "@treetasker" # required for Twitter Cards
